name: blog_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  velocity_x: ^4.1.2
  velocity_bloc: ^1.1.4
  shared_preferences: ^2.2.2
  auto_route: ^7.9.2
  google_fonts: ^6.2.0
  dio: ^5.4.1
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.1
  flutter_widget_from_html_core: ^0.14.11
  awesome_bottom_bar: ^1.2.4
  feather_icons: ^1.2.0
  flutter_screenutil: ^5.9.0
  animation_wrappers: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/constants/
  filename: app_assets.dart

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
